### ISSUE TITLE
remove dependency on cityscapes?

### ISSUE THREAD

**Issue by sofar** [minetest-mods/zombies#2]
Can you make this dependency optional? I don't like playing in artifical landscapes and I would like to have these spawn in the landscape without cityscapes installed.

**Comment by NathanSalapat** [comment]
ya, that can be made optional, I made it specifically for using with that mod, but I can see other people wanting to use it without.
I'll get the changes made later today.

**Comment by NathanSalapat** [comment]
Mod has been updated, cityscapes is now a soft depend.
Zombies only spawn on gravel in default game, so if you want more zombies you might want to place some gravel ;)
